wget https://graphchallenge.s3.amazonaws.com/synthetic/gc3/Theory-16-25-81-B1k.tsv
wget https://graphchallenge.s3.amazonaws.com/synthetic/gc3/Theory-16-25-B1k.tsv
wget https://graphchallenge.s3.amazonaws.com/synthetic/gc3/Theory-256-625-B1k.tsv
wget https://graphchallenge.s3.amazonaws.com/synthetic/gc3/Theory-25-81-256-B1k.tsv
wget https://graphchallenge.s3.amazonaws.com/synthetic/gc3/Theory-25-81-B1k.tsv
wget https://graphchallenge.s3.amazonaws.com/synthetic/gc3/Theory-3-4-5-9-16-25-B1k.tsv
wget https://graphchallenge.s3.amazonaws.com/synthetic/gc3/Theory-3-4-5-9-16-B1k.tsv
wget https://graphchallenge.s3.amazonaws.com/synthetic/gc3/Theory-3-4-5-9-B1k.tsv
wget https://graphchallenge.s3.amazonaws.com/synthetic/gc3/Theory-3-4-5-B1k.tsv
wget https://graphchallenge.s3.amazonaws.com/synthetic/gc3/Theory-3-4-B1k.tsv
wget https://graphchallenge.s3.amazonaws.com/synthetic/gc3/Theory-4-5-9-16-25-B1k.tsv
wget https://graphchallenge.s3.amazonaws.com/synthetic/gc3/Theory-4-5-9-16-B1k.tsv
wget https://graphchallenge.s3.amazonaws.com/synthetic/gc3/Theory-4-5-9-B1k.tsv
wget https://graphchallenge.s3.amazonaws.com/synthetic/gc3/Theory-4-5-B1k.tsv
wget https://graphchallenge.s3.amazonaws.com/synthetic/gc3/Theory-5-9-16-25-81-B1k.tsv
wget https://graphchallenge.s3.amazonaws.com/synthetic/gc3/Theory-5-9-16-25-B1k.tsv
wget https://graphchallenge.s3.amazonaws.com/synthetic/gc3/Theory-5-9-16-B1k.tsv
wget https://graphchallenge.s3.amazonaws.com/synthetic/gc3/Theory-5-9-B1k.tsv
wget https://graphchallenge.s3.amazonaws.com/synthetic/gc3/Theory-81-256-B1k.tsv
wget https://graphchallenge.s3.amazonaws.com/synthetic/gc3/Theory-9-16-25-81-B1k.tsv
wget https://graphchallenge.s3.amazonaws.com/synthetic/gc3/Theory-9-16-25-B1k.tsv
wget https://graphchallenge.s3.amazonaws.com/synthetic/gc3/Theory-9-16-B1k.tsv
