wget https://graphchallenge.s3.amazonaws.com/snap/amazon0302/amazon0302_adj.mmio
wget https://graphchallenge.s3.amazonaws.com/snap/amazon0312/amazon0312_adj.mmio
wget https://graphchallenge.s3.amazonaws.com/snap/amazon0505/amazon0505_adj.mmio
wget https://graphchallenge.s3.amazonaws.com/snap/amazon0601/amazon0601_adj.mmio
wget https://graphchallenge.s3.amazonaws.com/snap/as20000102/as20000102_adj.mmio
wget https://graphchallenge.s3.amazonaws.com/snap/as-caida20071105/as-caida20071105_adj.mmio
wget https://graphchallenge.s3.amazonaws.com/snap/ca-AstroPh/ca-AstroPh_adj.mmio
wget https://graphchallenge.s3.amazonaws.com/snap/ca-CondMat/ca-CondMat_adj.mmio
wget https://graphchallenge.s3.amazonaws.com/snap/ca-GrQc/ca-GrQc_adj.mmio
wget https://graphchallenge.s3.amazonaws.com/snap/ca-HepPh/ca-HepPh_adj.mmio
wget https://graphchallenge.s3.amazonaws.com/snap/ca-HepTh/ca-HepTh_adj.mmio
wget https://graphchallenge.s3.amazonaws.com/snap/cit-HepPh/cit-HepPh_adj.mmio
wget https://graphchallenge.s3.amazonaws.com/snap/cit-HepTh/cit-HepTh_adj.mmio
wget https://graphchallenge.s3.amazonaws.com/snap/cit-Patents/cit-Patents_adj.mmio
wget https://graphchallenge.s3.amazonaws.com/snap/email-Enron/email-Enron_adj.mmio
wget https://graphchallenge.s3.amazonaws.com/snap/email-EuAll/email-EuAll_adj.mmio
wget https://graphchallenge.s3.amazonaws.com/snap/facebook_combined/facebook_combined_adj.mmio
wget https://graphchallenge.s3.amazonaws.com/snap/flickrEdges/flickrEdges_adj.mmio
wget https://graphchallenge.s3.amazonaws.com/snap/friendster/friendster_adj.mmio.gz
wget https://graphchallenge.s3.amazonaws.com/snap/loc-brightkite_edges/loc-brightkite_edges_adj.mmio
wget https://graphchallenge.s3.amazonaws.com/snap/loc-gowalla_edges/loc-gowalla_edges_adj.mmio
wget https://graphchallenge.s3.amazonaws.com/snap/oregon1_010331/oregon1_010331_adj.mmio
wget https://graphchallenge.s3.amazonaws.com/snap/oregon1_010407/oregon1_010407_adj.mmio
wget https://graphchallenge.s3.amazonaws.com/snap/oregon1_010414/oregon1_010414_adj.mmio
wget https://graphchallenge.s3.amazonaws.com/snap/oregon1_010421/oregon1_010421_adj.mmio
wget https://graphchallenge.s3.amazonaws.com/snap/oregon1_010428/oregon1_010428_adj.mmio
wget https://graphchallenge.s3.amazonaws.com/snap/oregon1_010505/oregon1_010505_adj.mmio
wget https://graphchallenge.s3.amazonaws.com/snap/oregon1_010512/oregon1_010512_adj.mmio
wget https://graphchallenge.s3.amazonaws.com/snap/oregon1_010519/oregon1_010519_adj.mmio
wget https://graphchallenge.s3.amazonaws.com/snap/oregon1_010526/oregon1_010526_adj.mmio
wget https://graphchallenge.s3.amazonaws.com/snap/oregon2_010331/oregon2_010331_adj.mmio
wget https://graphchallenge.s3.amazonaws.com/snap/oregon2_010407/oregon2_010407_adj.mmio
wget https://graphchallenge.s3.amazonaws.com/snap/oregon2_010414/oregon2_010414_adj.mmio
wget https://graphchallenge.s3.amazonaws.com/snap/oregon2_010421/oregon2_010421_adj.mmio
wget https://graphchallenge.s3.amazonaws.com/snap/oregon2_010428/oregon2_010428_adj.mmio
wget https://graphchallenge.s3.amazonaws.com/snap/oregon2_010505/oregon2_010505_adj.mmio
wget https://graphchallenge.s3.amazonaws.com/snap/oregon2_010512/oregon2_010512_adj.mmio
wget https://graphchallenge.s3.amazonaws.com/snap/oregon2_010519/oregon2_010519_adj.mmio
wget https://graphchallenge.s3.amazonaws.com/snap/oregon2_010526/oregon2_010526_adj.mmio
wget https://graphchallenge.s3.amazonaws.com/snap/p2p-Gnutella04/p2p-Gnutella04_adj.mmio
wget https://graphchallenge.s3.amazonaws.com/snap/p2p-Gnutella05/p2p-Gnutella05_adj.mmio
wget https://graphchallenge.s3.amazonaws.com/snap/p2p-Gnutella06/p2p-Gnutella06_adj.mmio
wget https://graphchallenge.s3.amazonaws.com/snap/p2p-Gnutella08/p2p-Gnutella08_adj.mmio
wget https://graphchallenge.s3.amazonaws.com/snap/p2p-Gnutella09/p2p-Gnutella09_adj.mmio
wget https://graphchallenge.s3.amazonaws.com/snap/p2p-Gnutella24/p2p-Gnutella24_adj.mmio
wget https://graphchallenge.s3.amazonaws.com/snap/p2p-Gnutella25/p2p-Gnutella25_adj.mmio
wget https://graphchallenge.s3.amazonaws.com/snap/p2p-Gnutella30/p2p-Gnutella30_adj.mmio
wget https://graphchallenge.s3.amazonaws.com/snap/p2p-Gnutella31/p2p-Gnutella31_adj.mmio
wget https://graphchallenge.s3.amazonaws.com/snap/roadNet-CA/roadNet-CA_adj.mmio
wget https://graphchallenge.s3.amazonaws.com/snap/roadNet-PA/roadNet-PA_adj.mmio
wget https://graphchallenge.s3.amazonaws.com/snap/roadNet-TX/roadNet-TX_adj.mmio
wget https://graphchallenge.s3.amazonaws.com/snap/soc-Epinions1/soc-Epinions1_adj.mmio
wget https://graphchallenge.s3.amazonaws.com/snap/soc-Slashdot0811/soc-Slashdot0811_adj.mmio
wget https://graphchallenge.s3.amazonaws.com/snap/soc-Slashdot0902/soc-Slashdot0902_adj.mmio
