wget https://graphchallenge.s3.amazonaws.com/snap/amazon0302/amazon0302_inc.mmio
wget https://graphchallenge.s3.amazonaws.com/snap/amazon0312/amazon0312_inc.mmio
wget https://graphchallenge.s3.amazonaws.com/snap/amazon0505/amazon0505_inc.mmio
wget https://graphchallenge.s3.amazonaws.com/snap/amazon0601/amazon0601_inc.mmio
wget https://graphchallenge.s3.amazonaws.com/snap/as20000102/as20000102_inc.mmio
wget https://graphchallenge.s3.amazonaws.com/snap/as-caida20071105/as-caida20071105_inc.mmio
wget https://graphchallenge.s3.amazonaws.com/snap/ca-AstroPh/ca-AstroPh_inc.mmio
wget https://graphchallenge.s3.amazonaws.com/snap/ca-CondMat/ca-CondMat_inc.mmio
wget https://graphchallenge.s3.amazonaws.com/snap/ca-GrQc/ca-GrQc_inc.mmio
wget https://graphchallenge.s3.amazonaws.com/snap/ca-HepPh/ca-HepPh_inc.mmio
wget https://graphchallenge.s3.amazonaws.com/snap/ca-HepTh/ca-HepTh_inc.mmio
wget https://graphchallenge.s3.amazonaws.com/snap/cit-HepPh/cit-HepPh_inc.mmio
wget https://graphchallenge.s3.amazonaws.com/snap/cit-HepTh/cit-HepTh_inc.mmio
wget https://graphchallenge.s3.amazonaws.com/snap/cit-Patents/cit-Patents_inc.mmio
wget https://graphchallenge.s3.amazonaws.com/snap/email-Enron/email-Enron_inc.mmio
wget https://graphchallenge.s3.amazonaws.com/snap/email-EuAll/email-EuAll_inc.mmio
wget https://graphchallenge.s3.amazonaws.com/snap/facebook_combined/facebook_combined_inc.mmio
wget https://graphchallenge.s3.amazonaws.com/snap/flickrEdges/flickrEdges_inc.mmio
wget https://graphchallenge.s3.amazonaws.com/snap/friendster/friendster_inc.mmio.gz
wget https://graphchallenge.s3.amazonaws.com/snap/loc-brightkite_edges/loc-brightkite_edges_inc.mmio
wget https://graphchallenge.s3.amazonaws.com/snap/loc-gowalla_edges/loc-gowalla_edges_inc.mmio
wget https://graphchallenge.s3.amazonaws.com/snap/oregon1_010331/oregon1_010331_inc.mmio
wget https://graphchallenge.s3.amazonaws.com/snap/oregon1_010407/oregon1_010407_inc.mmio
wget https://graphchallenge.s3.amazonaws.com/snap/oregon1_010414/oregon1_010414_inc.mmio
wget https://graphchallenge.s3.amazonaws.com/snap/oregon1_010421/oregon1_010421_inc.mmio
wget https://graphchallenge.s3.amazonaws.com/snap/oregon1_010428/oregon1_010428_inc.mmio
wget https://graphchallenge.s3.amazonaws.com/snap/oregon1_010505/oregon1_010505_inc.mmio
wget https://graphchallenge.s3.amazonaws.com/snap/oregon1_010512/oregon1_010512_inc.mmio
wget https://graphchallenge.s3.amazonaws.com/snap/oregon1_010519/oregon1_010519_inc.mmio
wget https://graphchallenge.s3.amazonaws.com/snap/oregon1_010526/oregon1_010526_inc.mmio
wget https://graphchallenge.s3.amazonaws.com/snap/oregon2_010331/oregon2_010331_inc.mmio
wget https://graphchallenge.s3.amazonaws.com/snap/oregon2_010407/oregon2_010407_inc.mmio
wget https://graphchallenge.s3.amazonaws.com/snap/oregon2_010414/oregon2_010414_inc.mmio
wget https://graphchallenge.s3.amazonaws.com/snap/oregon2_010421/oregon2_010421_inc.mmio
wget https://graphchallenge.s3.amazonaws.com/snap/oregon2_010428/oregon2_010428_inc.mmio
wget https://graphchallenge.s3.amazonaws.com/snap/oregon2_010505/oregon2_010505_inc.mmio
wget https://graphchallenge.s3.amazonaws.com/snap/oregon2_010512/oregon2_010512_inc.mmio
wget https://graphchallenge.s3.amazonaws.com/snap/oregon2_010519/oregon2_010519_inc.mmio
wget https://graphchallenge.s3.amazonaws.com/snap/oregon2_010526/oregon2_010526_inc.mmio
wget https://graphchallenge.s3.amazonaws.com/snap/p2p-Gnutella04/p2p-Gnutella04_inc.mmio
wget https://graphchallenge.s3.amazonaws.com/snap/p2p-Gnutella05/p2p-Gnutella05_inc.mmio
wget https://graphchallenge.s3.amazonaws.com/snap/p2p-Gnutella06/p2p-Gnutella06_inc.mmio
wget https://graphchallenge.s3.amazonaws.com/snap/p2p-Gnutella08/p2p-Gnutella08_inc.mmio
wget https://graphchallenge.s3.amazonaws.com/snap/p2p-Gnutella09/p2p-Gnutella09_inc.mmio
wget https://graphchallenge.s3.amazonaws.com/snap/p2p-Gnutella24/p2p-Gnutella24_inc.mmio
wget https://graphchallenge.s3.amazonaws.com/snap/p2p-Gnutella25/p2p-Gnutella25_inc.mmio
wget https://graphchallenge.s3.amazonaws.com/snap/p2p-Gnutella30/p2p-Gnutella30_inc.mmio
wget https://graphchallenge.s3.amazonaws.com/snap/p2p-Gnutella31/p2p-Gnutella31_inc.mmio
wget https://graphchallenge.s3.amazonaws.com/snap/roadNet-CA/roadNet-CA_inc.mmio
wget https://graphchallenge.s3.amazonaws.com/snap/roadNet-PA/roadNet-PA_inc.mmio
wget https://graphchallenge.s3.amazonaws.com/snap/roadNet-TX/roadNet-TX_inc.mmio
wget https://graphchallenge.s3.amazonaws.com/snap/soc-Epinions1/soc-Epinions1_inc.mmio
wget https://graphchallenge.s3.amazonaws.com/snap/soc-Slashdot0811/soc-Slashdot0811_inc.mmio
wget https://graphchallenge.s3.amazonaws.com/snap/soc-Slashdot0902/soc-Slashdot0902_inc.mmio
